# Generated by Django 5.0.3 on 2024-04-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('IdNumber', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomNo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('IdNumber', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nurse',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField(max_length=100)),
                ('patientId', models.CharField(max_length=100, unique=True)),
                ('nida', models.CharField(max_length=100, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('date', models.DateField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
